server:
  port: 8089
spring:
  application:
    name: goods
#goods:
#  rabbion:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
##服务注册到中心地址
eureka:
  client:
    service-url:
      defaultZone: http://lin:123456@127.0.0.1:8088/eureka
      ##注册到注册中心
    register-with-eureka: true
    #检索服务
    fetch-registry: true

